package com.myLearning.springApp.dto;

import org.springframework.data.mongodb.core.mapping.Document;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

//creating this for transferring one data layer to another data layer
//will be generated by mongodb

@Document
@Data
@AllArgsConstructor
@NoArgsConstructor
public class CustomerDTO {
	
    private String id;	
	private Integer customerNumber;
	private String name;
	private String city;
	private String state;	
	private Integer billAmount;	

}
