package com.myLearning.springApp.dto;

import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


//creating this for transferring one data layer to another data layer
//will be generated by mongodb

@Document
@Data
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class CustomerDTO {
	
    private String id;	
	private Integer customerNumber;
	private String name;
	private String city;
	private String state;		

}
